routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/taxpayer/stats', 'TaxpayerController@stats');

Route::get('/taxpayer/import', 'TaxpayerController@import');
Route::get('/taxpayer/importData', 'TaxpayerController@importData');
Route::post('/taxpayer/importData', 'TaxpayerController@importData');

Route::resource('taxpayer', 'TaxpayerController');
  
Auth::routes();

Route::get('/upload', 'TaxpayerController@upload');
Route::post('/upload/proses', 'TaxpayerController@proses_upload');

resources/views/inc/leaflet/base.blade.php
<script>
    var nonLabeledWorldStreet = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}', {
        maxZoom: 19,
        gestureHandling: true,
        attribution: 'Tiles &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012'
    });
    
    var labeledWorldStreet = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        gestureHandling: true,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    });

    var mapCenter = [{{  $taxpayer->lat ?? (request('latitude') ?? -4.0185)  }}, {{ $taxpayer->long ?? (request('longitude') ?? 119.6710) }}];
    
    var map = L.map('mapid', {
        gestureHandling: true, 
        layers: [nonLabeledWorldStreet]
    })

    .setView(mapCenter, 12);
    var baseUrl = "{{ url('/') }}";
    var baseMaps = {
        "Grayscale": nonLabeledWorldStreet,
        "Streets": labeledWorldStreet
    };

</script>

resources/views/inc/leaflet/formUpdate.blade.php
<script>
    // Update Latitude and Longitude Form via clicking the map
    map.on('click', function(e) {
        let lat = e.latlng.lat.toString().substring(0, 15);
        let long = e.latlng.lng.toString().substring(0, 15);
        
        $('#latitude').val(lat);
        $('#longitude').val(long);
        updateMarker(lat, long);
    });
    
    var updateMarkerByInputs = function() {
        return updateMarker( $('#latitude').val() , $('#longitude').val());
    }
    
    $('#latitude').on('input', updateMarkerByInputs);
    $('#longitude').on('input', updateMarkerByInputs);
</script>

resources/views/inc/leaflet/gesture.blade.php
    <!-- Gesture Handling -->
    <link rel="stylesheet" href="//unpkg.com/leaflet-gesture-handling/dist/leaflet-gesture-handling.min.css" type="text/css">
    <script src="//unpkg.com/leaflet-gesture-handling"></script>

resources/views/inc/leaflet/hover.blade.php
<script>
    var info = L.control();
    
    info.onAdd = function (map) {
        return this.updatesidebar();
    };
    
    info.updatesidebar = function (props) {
        document.getElementById("mySidenav").innerHTML = '<a href="javascript:void(0)" class="closebtn" onclick="closesidebar()">&times;</a><h2>Kota Parepare</h2></br><h4>' + props.NAME_4+'</h4>';
    };
    
    // method that we will use to update the control based on feature properties passed    
    
    info.addTo(map);
</script>

resources/views/inc/leaflet/icons.blade.php
<script>
    var Icons = L.Icon.extend({
        options: {
            shadowUrl: '{{URL::asset("/map-marker/shadow-64.png")}}',
            iconSize:     [32, 32],
            shadowSize:   [32, 32],
            iconAnchor:   [16, 32],
            shadowAnchor: [16, 32],
            popupAnchor:  [0, -32]
        }
    });
    
    var restaurantIcon = new Icons({iconUrl: '{{URL::asset("/map-marker/restaurant-64.png")}}'}),
    propertyIcon = new Icons({iconUrl: '{{URL::asset("/map-marker/property-64-3.png")}}'}),
    parkingIcon = new Icons({iconUrl: '{{URL::asset("/map-marker/parking-64-2.png")}}'}),
    hotelIcon = new Icons({iconUrl: '{{URL::asset("/map-marker/hotel-64-4.png")}}'});
</script>

resources/views/inc/leaflet/imports.blade.php
 <!-- Leaflet css -->
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
 integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
 crossorigin=""/>
 
 <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
 integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
 crossorigin=""></script>
 <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-ajax/2.1.0/leaflet.ajax.js"></script>

resources/views/inc/leaflet/layers.blade.php
<script>
    var defaultLayout = new L.GeoJSON.AJAX();
    var regionLayout = new L.GeoJSON.AJAX("{{URL::asset('taxpayer.json')}}");
    var totalLayout = new L.GeoJSON.AJAX("{{URL::asset('taxpayer.json')}}",{style: style, onEachFeature: onEachFeature});
    var restaurantLayout = new L.GeoJSON.AJAX("{{URL::asset('taxpayer.json')}}",{style: style, onEachFeature: onEachFeature});
    var hotelLayout = new L.GeoJSON.AJAX("{{URL::asset('taxpayer.json')}}",{style: style, onEachFeature: onEachFeature});
    var parkingLayout = new L.GeoJSON.AJAX("{{URL::asset('taxpayer.json')}}",{style: style, onEachFeature: onEachFeature});
    var propertyLayout = new L.GeoJSON.AJAX("{{URL::asset('taxpayer.json')}}",{style: style, onEachFeature: onEachFeature});
    
    var layer = {
        "NONE"       : defaultLayout.addTo(map),
        "KELURAHAN"  : regionLayout,
        "TOTAL "     : totalLayout,
        "RESTAURANT" : restaurantLayout,
        "HOTEL"      : hotelLayout,
        "PARKIR"     : parkingLayout,
        "PBB"        : propertyLayout
    };
    L.control.layers(layer, overlayMaps).addTo(map);
    
    function highlightFeature(e) {
        var layer = e.target;
        
        layer.setStyle({
            weight: 5,
            color: '#666',
            dashArray: '',
            fillOpacity: 0.7
        });
        
        if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
            layer.bringToFront();
        }
        //infosidebar.updatesidebar(layer.feature.properties);
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("mapid").style.marginLeft = "250px";
        info.updatesidebar(layer.feature.properties); 
    }
    
    function highlightNear(e) {
        var layer = e.target;
        
        layer.setStyle({
            weight: 5,
            color: '#666',
            dashArray: '',
            fillOpacity: 0.7
        });
        
        if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
            layer.bringToFront();
        }
    }
    
    function resetHighlight(e) {
        defaultLayout.resetStyle(e.target);
        regionLayout.resetStyle(e.target);
        totalLayout.resetStyle(e.target);
        restaurantLayout.resetStyle(e.target);
        hotelLayout.resetStyle(e.target);
        parkingLayout.resetStyle(e.target);
        taxpayerLayout.resetStyle(e.target);
        document.getElementById("mySidenav").style.width = "0";
        document.getElementById("mapid").style.marginLeft = "0";
        info.updatesidebar();
    }
    
    function closesidebar(){
        document.getElementById("mySidenav").style.width = "0";
        document.getElementById("mapid").style.marginLeft = "0";
        info.updatesidebar();
    }
    
    function resetLine(e) {
        defaultLayout.resetStyle(e.target);
        regionLayout.resetStyle(e.target);
        totalLayout.resetStyle(e.target);
        restaurantLayout.resetStyle(e.target);
        hotelLayout.resetStyle(e.target);
        parkingLayout.resetStyle(e.target);
        taxpayerLayout.resetStyle(e.target);
    }
    
    function zoomToFeature(e) {
        map.fitBounds(e.target.getBounds());
    }
    
    function onEachFeature(feature, layer) {
        layer.on({
            mouseover : highlightNear,
            mouseout: resetLine,
            click: highlightFeature
        });
    }
    
    function style(feature) {
        return {
            fillColor: getColor(feature.properties.pajak_per_bulan),
            weight: 2,
            opacity: 1,
            color: 'white',
            dashArray: '3',
            fillOpacity: 0.7
        };
    }
    
</script>

resources/views/inc/leaflet/legend.blade.php
<script>
    //From Lighter to Darker color
    var colors = ['#fff5eb', '#fee6ce', '#fdd0a2', '#fdae6b', '#fd8d3c', '#f16913', '#d94801', '#8c2d04'];
    //From Low to High
    var grades = [0, 500000, 1000000, 2500000, 5000000, 10000000, 25000000, 50000000]
    
    function getColor(pajak) {
        return  pajak > grades[7] ? colors[7] :
                pajak > grades[6] ? colors[6] :
                pajak > grades[5] ? colors[5] :
                pajak > grades[4] ? colors[4] :
                pajak > grades[3] ? colors[3] :
                pajak > grades[2] ? colors[2] :
                pajak > grades[1] ? colors[1] :
                                    colors[0] ;
    }

    var legend = L.control({position: 'bottomright'});
    legend.onAdd = function (map) {
        
        var div = L.DomUtil.create('div', 'info legend');
        
        // loop through our density intervals and generate a label with a colored square for each interval
        for (var i = 0; i < grades.length; i++) {
            div.innerHTML +=
            '<i style="background:' + getColor(grades[i] + 1) + '"></i> ' +
            grades[i] + (grades[i + 1] ? '&ndash;' + grades[i + 1] + '<br>' : '+');
        }
        
        return div;
    };
    legend.addTo(map);
        
</script>

resources/views/inc/leaflet/maps.blade.php
<script>
    var nonLabeledWorldStreet = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}', {
        minZoom: 12,
        maxZoom: 19,
        gestureHandling: true,
        attribution: 'Tiles &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012'
    });
    
    var labeledWorldStreet = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        gestureHandling: true,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    });

    var mapboxlayer = L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
        maxZoom: 19,
        gestureHandling: true,
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' + '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' + 'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>'
    });
    
</script>

resources/views/inc/leaflet/popupCreateTaxpayer.blade.php
<script>
    var theMarker;
    map.on('click', function(e) {
            let latitude = e.latlng.lat.toString().substring(0, 15);
            let longitude = e.latlng.lng.toString().substring(0, 15);
            if (theMarker != undefined) {
                map.removeLayer(theMarker);
            };
            
            var popupContent = "Your location : " + latitude + ", " + longitude + ".";
            popupContent += '<br><a href="{{ route('taxpayer.create') }}?latitude=' + latitude + '&longitude=' + longitude + '">Add new taxpayer here</a>';
            
            theMarker = L.marker([latitude, longitude]).addTo(map);
            theMarker.bindPopup(popupContent)
            .openPopup();
        });
</script>

resources/views/inc/leaflet/removeMarkerOnPopupClose.blade.php
<script>
    map.on('popupclose', function(e) {
        if (theMarker != undefined) {
            map.removeLayer(theMarker);
        };
    });
</script>

resources/views/inc/leaflet/sidebar.blade.php
<style>
        .sidenav {
              height: 100%; /* 100% Full-height */
              width: 0; /* 0 width - change this with JavaScript */
              position: fixed; /* Stay in place */
              z-index: 1000; /* Stay on top */
              top: 0; /* Stay at the top */
              left: 0;
              /*background-color: #777;  Black*/
              overflow-y: auto; /* Disable horizontal scroll */
              padding-top: 60px; /* Place content 60px from the top */
              transition: 0.5s; /* 0.5 second transition effect to slide in the sidenav */
              padding-left:10px;
          }

          /* The navigation menu links */
        .sidenav a {
          
          text-decoration: none;
          font-size: 25px;
          color: #818181;
          display: block;
          transition: 0.3s;
        }


        .sidenav a:hover {
          color: #f1f1f1;
        }


        .sidenav .closebtn {
          position: absolute;
          top: 0;
          right: 25px;
          font-size: 36px;
          margin-left: 50px;
        }

        @media screen and (max-width: 700px) {
          .sidenav {
            padding-top: 15px;
          }
          .sidenav a {
            font-size: 18px;
          }
          .sidenav a:hover{
            width:100%;
          }
        }
        
</style>

resources/views/inc/leaflet/style.blade.php
<style>
    .legend i {
        width: 18px;
        height: 18px;
        float: left;
        margin-right: 8px;
        opacity: 0.7;
    }
    .info {
        padding: 6px 8px;
        background: white;
        background: rgba(255,255,255,0.8);
        box-shadow: 0 0 15px rgba(0,0,0,0.2);
        border-radius: 5px;
    }

    .info h4 {
        margin: 0 0 5px;
        color: #777;
    }
    
    .leaflet-popup-pane, .leaflet-control {
        cursor: auto;
    }
</style>